apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is dan open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: teama
  lifecycle: production
  providesApis:
    - backstage-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-service
  description: |
    backstage-service
spec:
  type: service
  owner: teama
  lifecycle: production
  consumesApis:
    - backstage-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-consumer
  description: |
    Consumes data of backstage
spec:
  type: library
  owner: teama
  lifecycle: production
  consumesApis:
    - backstage-api

---  
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api
  description: waste cpu cycle
spec:
  type: openapi
  lifecycle: production
  owner: teama
  definition: |
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/wayback/1.0.0/openapi.yaml
    paths: {}

