apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: CNCF
  description: CNCF
spec:
  type: team
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  members: [jdoe]
